### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/bolt#100]
I'm finding that error handling is not a particular strength of the Bolt compiler. For the most part, when I have an error in my bolt file, it can direct me to the line (or near the line) of code that is causing the issue, but the message is typically a generic:

    bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "f"/"p"/"t" found.

This already bit me once #98, and although it was *quite* a silly mistake on my part, for some reason my eyes could *not* see the (now) very apparent error. 

I haven't seen a singular location where errors that cause the generic error to be issued are listed (there maybe an internal list), but I think it would help if there was something public that users could contribute to when they stumble.

**LIST OF ERROR MESSAGES TO BE IMPROVED**:

| # | Description | Error Statement Received | Improved Error Statement |
| ---------------- | ------------------------------------ | ------------------------------------ | -------------------- |
| 1 | In *path* statements, `read()`, `write()`, and `validate()` functions must be immediately proceeded with an equals sign, *not* a colon. | bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "p" found. | `read()`, `write()`, and `validate()` was not proceeded by "=", instead ":" found. | |
| 2 | For an equality check, something other than a double- or triple-equals sign (i.e. a single equals sign) will generate an error | bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "f" found. | Unknown operator "=" used. Did you mean "=="? | |
| 3 | Missing semicolon after end of `read()`, `write()`, or `validate()` | bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "p" found. | Missing semicolon after `read()`/`write()`/`validate()` statement |
| 4 | In *type* statements, a key with a hyphen generates an error | bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "t" found. | **This should not be an error** |

I'll continue to add onto this as I come across more of these, and I'll to the main table as others comment as well.

Hope this is useful...

Contributions:

- No. 3 contributed by @jacob-israel-turner

**Comment by mckoss** [comment]
Agreed!  Thanks for the useful specific suggestions!
