### ISSUE TITLE
Make property optional

### ISSUE THREAD

**Issue by jacob-israel-turner** [firebase/bolt#102]
I'm reading the docs now and it seems that anywhere I place a new property (e.g., under a user, validating an `info` property), it adds this to the parent property:

``` json
"$userid": {
  ".validate": "newData.hasChildren(['info'])"
  (...)
}
```

Is there any way I can add validation for a property, while allowing that property to remain optional?

**Comment by jacob-israel-turner** [comment]
I think I may have found a way around this.  Here is what I have written:

```
path /users/$userid is User;

type User {
  info: UserInfo,
}

type UserInfo {
  avatar: String,
  banned: Boolean,
  bio: String,
  birthday: Number,
  cancerCategory: String,
}
```

Which compiles to:

``` json
{
  "rules": {
    "users": {
      "$userid": {
        ".validate": "newData.hasChildren(['info'])",
        "info": {
          ".validate": "newData.hasChildren(['avatar', 'banned', 'bio', 'birthday', 'cancerCategory'])",
          "avatar": {
            ".validate": "newData.isString()"
          },
          "banned": {
            ".validate": "newData.isBoolean()"
          },
          "bio": {
            ".validate": "newData.isString()"
          },
          "birthday": {
            ".validate": "newData.isNumber()"
          },
          "cancerCategory": {
            ".validate": "newData.isString()"
          },
          "$other": {
            ".validate": "false"
          }
        },
        "$other": {
          ".validate": "false"
        }
      }
    }
  }
}
```

I suppose if I changed that from a nested schema to validating info by its own path, it wouldn't add `".validate": "newData.hasChildren(['info'])"` to the user.  Is this the best/only way around a property being mandatory?

**Comment by mckoss** [comment]
You can have [optional properties](https://github.com/firebase/bolt/blob/master/docs/language.md#union-types) by allowing them to be Null.

```
type User {
  info: UserInfo | Null;
}
```

**Comment by jacob-israel-turner** [comment]
Ah, great.  Thanks @mckoss!
