### ISSUE TITLE
In type statement, keys without quotes cannot have hyphens (bug?)

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/bolt#107]
As described in #100 No. 4, a *type* statement with a key that has a hyphen/dash will generate the following error:

```
type SomeType {
  Key-With-Dashes: Number
}

bolt:LINE_NUM:COL_NUM: Expected comment, end of input, function definition, path statement, type statement or whitespace but "t" found.
```

The error goes away if the key is enclosed in quotes (that is the workaround for now):

```
type SomeType {
  "Key-With-Dashes": Number
}

//No error
```

I didn't see anything in the docs about limitations on key names when not surrounded in quotes (obviously, things like spaces wouldn't work, but I would think a dash would). Is this the desired behavior?

**Comment by mckoss** [comment]
This is by design.  I added documentation about allowed characters in strings and identifiers in commit d51a1ee93befe9d8c17d93700add20abcfc3b99e
