### ISSUE TITLE
Are Firebase rules permissive or fully locked out by default? Docs and explanations conflict

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/bolt#108]
As described in the [Bolt docs](https://github.com/firebase/bolt/blob/master/docs/guide.md):

> By default, Firebase has a permissive security model; everyone can read and write all data.

and in the [Firebase docs](https://www.firebase.com/docs/security/quickstart.html):

> By default, your app has rules which grants every request full read and write permissions to your database:

Firebase security rules are explained as *permissive* by default, but, in @mckoss's explanation to #97, I see a conflicting story:

> Firebase is read==false and write==false by default, so there is no need for this.

**So, which is it?**

I *think* I understand the issue:

When you start a new Firebase, the security rules that are loaded by default are the following:

```
"rules": {
  ".read": true,
  ".write": true
}
```

So, that is what is meant by the first two quotes that come from the docs which *generates confusion* because what @mckoss is saying is that, if the rules file is actually empty:

```
"rules": {}
```

Then that actually translates to:

```
"rules": {
  ".read": false,
  ".write": false
}
```

The Bolt and Firebase docs should probably be updated to clear this up.

**Comment by mckoss** [comment]
Good point - I can see how that can cause confusion.

Is this better?

https://github.com/firebase/bolt/blob/koss-rules-docs/docs/guide.md

**Comment by mm-gmbd** [comment]
That's actually probably the best I've seen it explained, especially the bit about how validation is actually an **AND** of all the validations at that location and higher. 

From the [Firebase docs on validation](https://www.firebase.com/docs/security/api/rule/validate.html):

> A .validate rule is used once a .write rule has granted access, to ensure that the data being written conforms to a specific standard. In addition to a .write granting access, **all relevant .validate rules must succeed before a write is allowed**.

The phrasing of "*all relevant .validate rules*" is **very** vague.

I've gathered this through testing and through some emails back and forth with Firebase support, but the way you've laid it out is very digestible.

**Comment by mckoss** [comment]
Thanks for the suggestion and review!

**Comment by mm-gmbd** [comment]
@mckoss, quick question about the explanation of "validation at that location and higher".

Say I have the following data structure:

```
path /data is Data {
  write() = true;
}

type Data {
  key1: Number,
  key2: String,
  key3: Boolean
}
```

Notice that none of the keys are OR'd with Null, so a write to `/data` will have a validation rule that all three keys are included as children (`newData.hasChildren(['key1', 'key2', 'key3'])`).

Now, if I decided to write to `/data/key1`, I would guess that I would be able to considering the parent location (`/data`) write rule grants write access, therefore granting write access at children (however the validation at the child level still applies). But, obviously the parent rule of `newData.hasChildren()` cannot apply as I am only writing to *one* of the child locations.

I presume that Firebase rules ignore this rule when performing "up-the-chain" validation? Are there other rules that follow this manner? Thanks!
