### ISSUE TITLE
"Type[] | Null" produces incorrect rules

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/bolt#118]
The following Bolt rules:

```
type Something {
  A: Boolean,
  B: Number[] | Null
}

path /path is Something {
  read() = true;
}
```

produce the following rules json:

```
{
  "rules": {
    "path": {
      ".validate": "newData.hasChildren(['A'])",
      "A": {
        ".validate": "newData.isBoolean()"
      },
      "B": {
        "$key1": {
          ".validate": "newData.isNumber()"
        },
        ".validate": "newData.val() == null"
      },
      "$other": {
        ".validate": "false"
      },
      ".read": "true"
    }
  }
}
```

Notice the rules for **`B`**. It correctly produces the map rule ensuring that all wildcarded children are numbers, but it also produces a rule for **`B`** itself, validation that `newData.val() == null`. This precludes me from being able to write anything at `/path/B`!

I think the desired behavior would be, when encountered with an `Type[] | Null`, it would not produce any validation at the level of `Type`.

**Comment by mm-gmbd** [comment]
It looks like the fix is to remove `| Null` entirely. I had thought this would make the `.validate` rules at `path` equivalent to the following:

```
"path": {
  ".validate": "newData.hasChildren(['A', 'B'])"
}
```

But it was smart enough to discard the `'B'`. Still, probably would be less confusing to allow for `Type[] | Null`!

**Comment by mckoss** [comment]
Another test case:
```
path /x is String | Null;
path /y is String[];
path /z is String[] | Null;
```
produces:
```
{
  "rules": {
    "x": {
      ".validate": "newData.isString() || newData.val() == null"
    },
    "y": {
      "$key1": {
        ".validate": "newData.isString()"
      }
    },
    "z": {
      "$key1": {
        ".validate": "newData.isString()"
      },
      ".validate": "newData.val() == null"
    }
  }
}
```

**Comment by jacob-israel-turner** [comment]
I experienced this today.  Commenting to follow the issue.

**Comment by YeomansIII** [comment]
Also having this issue, any progress on allowing Map | Null?

**Comment by nhim175** [comment]
I got the same issue today. Is there any work around for this?
