### ISSUE TITLE
Updating Types

### ISSUE THREAD

**Issue by ziaukhan** [firebase/bolt#128]
When we define a MyType in Bolt:

type MyType {
   field1 : String,
   field2: String,
   field3: String,
   field4: String | Null
}

it will basically creates this for all the required fields, and ignoring optional fields:

".validate": "newData.hasChildren(['field1', 'field2', 'field3'])",
 
When create a MyType will make sure that all three fields are present in the data which is ok. The problem is when we update just say field3 it will not allow us to just update field3. If we are using the JavaScript SDK this is ok we will update all the fields even if they are not changed (but if we just change one filed it will not allow us). But when we are using AngularFire $save() method it updates only the changed fields thus the rules fail and we cannot update the object.

**Comment by MOHAMMADArsalan** [comment]
yes, I am having the problem

**Comment by Taimoor123** [comment]
me to.

**Comment by ziaukhan** [comment]
I have a not a very elegant workaround:
1. Make all fields in a type optional.
2. in the create() method add a rule this.hasChildren for all the required fields.
But the problem with this is that in the update u can delete the required fields :(

**Comment by mckoss** [comment]
Actually, I think Bolt caught a bug in the way you are writing the database and prevented you from corrupting your data.  @puf tells me:
-----
AngularFire's $save() calls set() under the hood. So it's not an performing an update, but replacing everything. It's a good thing the security rules prevent that. :-)

The solution is to do: obj.$ref().update({ field3: 'new value' });

**Comment by smkamranqadri** [comment]
@mckoss is correct, here is the jsfiddle for easy reference.

**Comment by lukepighetti** [comment]
Hey guys, I just ran into this in 2018 and I'm having the same problem, but using `.update()` doesn't seem to be resolving it.
