### ISSUE TITLE
root object available in read(), not in write() ?

### ISSUE THREAD

**Issue by pandaiolo** [firebase/bolt#135]
Here is my `rules.bolt` file: 

    path / {
        read() { isAdmin() }
        write() { isAdmin() }
    }

    isAdmin() { root.usersMeta[auth.uid].isAdmin == true }

The resulting `rules.json`:

    {
      "rules": {
        ".read": "root.child('usersMeta').child(auth.uid).child('isAdmin').val() == true",
        ".write": "newData.child('usersMeta').child(auth.uid).child('isAdmin').val() == true"
      }
    }

Is this expected? 

If yes, what am I doing wrong? If no, any workaround?

Version: 0.8.0

**Comment by pandaiolo** [comment]
I guess the rule is working, as the rule is at the top level - I just noticed that `root` is replaced by `.parent().parent().parent()` in some other places.

However, it's a bit confusing, and I'd still like to know why the `read()` and `write()` get different after compiling.

Thanks !

**Comment by mckoss** [comment]
In a write rule, you can use prior(root) to get the same behavior as "root" in a read rule.

The reason for the different treatment is to support [multi-location updates)[https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html] since there is no "newRoot" variable in the JSON language.

**Comment by brianneisler** [comment]
@mckoss this is an awesome bit of capability. Have been finding myself passing around references like `this.parent().parent().parent()` to function calls (specifically for multi-location updates) because i didn't realize you could reference `root` in a write rule and it would do that for you. Very cool!

**Comment by mckoss** [comment]
Yes - this was implemented to support easier access to newData for multi-location updates (any reference to root in a write or validate rule, will convert to newData.parent()*).

```
path /foo/bar { validate() { root.bazz == 1} }
```

becomes

```
{
  "rules": {
    "foo": {
      "bar": {
        ".validate": "newData.parent().parent().child('bazz').val() == 1"
      }
    }
  }
}
```
