### ISSUE TITLE
String functions error when passed data argument

### ISSUE THREAD

**Issue by mhuebert** [firebase/bolt#136]
I believe this is either a bug or undocumented behaviour affecting all Firebase rules, but am re-posting the issue here as I haven't received any confirmation of that in the google group (https://groups.google.com/forum/#!topic/firebase-talk/f7VI2HGv17Q) and others may run into the same thing while using bolt.

From the String page (https://www.firebase.com/docs/security/api/string/) I’m led to believe that we can use string operations on anything that would resolve to a string at runtime. But when I try to use “some-string”.contains(this.someProperty) I get the error:  `contains() expects a string argument` when I attempt to deploy from the command line.

Full example:

```js
type Entity {
    entityType: String
}

path /entity/{entity} is Entity {
    validate(){
        "project|user".contains(this.entityType)
    }
}
// Error:  Rules Syntax Error: 1:xx: contains() expects a string argument.
```

**Comment by mckoss** [comment]
This is a bug in that Bolt does not realize the argument to contains needs to be a string.  As a work-around, appending '' forces the coercion (let me know if this works for you):

```
type Entity {
    entityType: String
}

path /entity/{entity} is Entity {
    validate(){
        "project|user".contains(this.entityType + '')
    }
}
```

**Comment by mckoss** [comment]
If you check the [Language Doc](https://github.com/firebase/bolt/blob/master/docs/language.md), you'll see that the proper Bolt function is 'includes', not 'contains' - in which case the correct JSON is generated.

Bolt should be generating warnings for un-recognized functions (I'll add an issue to track that as a feature request).
