### ISSUE TITLE
Support conditional rules using firebase's ternary operator '?'

### ISSUE THREAD

**Issue by brianneisler** [firebase/bolt#141]
It seems that firebase allows for conditional rules using the built in ternary operator. 

https://www.firebase.com/docs/security/api/operators/ternary.html

This could be used by bolt to provide an 'if' statement in the rules for creating conditional rules.

Take the following for example from the firebase website.
```
".validate": "newData.isNumber() ? newData.val() > 0 : newData.isBoolean()"
```

would cleanly transfer to bolt in the form
```
validate() {
  if (isNumber(this)) {
    return this > 0;
  }
  return isBoolean(this);
}
```

This is a trivial example but would allow for the writing of much more complex logic which is currently impossible with bolt and not easy to manage in firebase rules.

**Comment by mckoss** [comment]
We probably won't be adding non single-expression rules in Bolt as this would require flow analysis, etc.  For what its worth, you can use the ternary operator in Bolt as well:

```
path /test { validate() { this.isNumber() ? this > 0 : this.isBoolean() } }
```
