### ISSUE TITLE
Pass a regex variable to String.matches()

### ISSUE THREAD

**Issue by spirylics** [firebase/bolt#143]
Hi,
Is it possible to pass a variable instead of litteral regex to matches function of String ? 
It could be useful to describe dynamically security rules.

Thanks,

**Comment by brianneisler** [comment]
@spirylics I agree variables would be a nice addition. In the interim, you can hack constants together by using functions which is nice if you're reusing your regex's in several places.

```
function FOO() {
  return /^foo/;
}
```

**Comment by spirylics** [comment]
Thanks @brianneisler functions are interessing but don't resolve my problem because my regex comes from a child. I don't know if a workaround exists ?

**Comment by brianneisler** [comment]
@spirylics could you provide an example of what you are trying to do? Might be able to help yo figure out a workaround.

**Comment by spirylics** [comment]
@brianneisler , I would like to have a security like that : 
".write": "auth.roles.matches(root.child('meta').val())"

Thanks,

**Comment by spirylics** [comment]
up, @brianneisler do you have an idea ?

**Comment by brianneisler** [comment]
@spirylics unfortunately I don't think it's possible to dynamically bring in a regex statement from the db since there's no way to declare a regex as a string in firebase rules. Might be a good feature request for Firebase.

**Comment by mckoss** [comment]
@brianneisler is right - this is not a Bolt issue - but a feature request for firebase (JSON) rules to support variable regexes.
