### ISSUE TITLE
update() renders root erroneously 

### ISSUE THREAD

**Issue by foffer** [firebase/bolt#144]
For the following, the `read() { isAppAdmin(auth.uid) }` renders as: `"root.child('appRoles').child(auth.uid).child('role').val() == 'admin'`

where as `update() { isAppAdmin... }` renders `newData.parent().parent().child('appRoles')...` which doesn't work / allow the write
```
path /appRoles/{uid} is AppRole {
  create() { isCurrentUser(uid) }
  update() { isAppAdmin(auth.uid) }
  read() { isAppAdmin(auth.uid) || isCurrentUser(uid) }
  index() { return ["role"] }
}
```

**Comment by farmio** [comment]
#87 explains why root renders differently in read() and write() / update() functions.
