### ISSUE TITLE
Please add this to AngularFire2, cli and create a plugin to add to the angular-cli. 

### ISSUE THREAD

**Issue by lokeshjainRL** [firebase/bolt#145]
Thanks for this great module.

I like this very much. This can be integrated into the core projects. 

I just want to know your road with this small amazing utility.

**Comment by canesin** [comment]
No commits since January is a bit scary. Is this going forward with all the changes that are happening in firebase ?

**Comment by mckoss** [comment]
Bolt will likely remain an independent utility for now (I'm glad you like it).  I'm triaging issues now after a long hiatus; I'm looking to bring it up to date with the 3.0 SDK among other things.
