### ISSUE TITLE
Rules for enabling create with map but not update

### ISSUE THREAD

**Issue by startswithaj** [firebase/bolt#146]
I'm trying to create rules that allow an admin to write multiple entries to a map on different occasions. These entries should never be updated. I want the user to be able to read them and then delete them individually. 

With the rules below admin can write once to the map but further writes I get permission denied. 

It makes sense that the additional writes get permission denied. I guess what I'm asking is what is the appropriate data type/path that allows wildcarded $uid and wildcarded $requestID. 

```
path /user/responses/{$uid} is Map<RequestID, QueueResponse> {
  read()     { isCurrentUser($uid) }
  create()    { isAdmin()}
  delete()    { isCurrentUser($uid) }
}
```
Should I be doing something like this?

```
path /user/responses/{$uid} 
    /{$requestID} is QueueResponse {
     read()     { isCurrentUser($uid) }
     create()    { isAdmin()}
     delete()    { isCurrentUser($uid) }
  }
}
```
Since version 3.0 debugging this is further complicated because there is no way to encode a debug flag into the admin token, we are now using service accounts. I have seen a few posts on SO and the like suggesting firebase.database.enableLogging(true) but this is not the same. It does not print failure reason.

**Comment by mckoss** [comment]
Both of your examples look equivalent to me.  The only reason to use the Map<> form would be to ensure some type checking on the key string (RequestID) - if it's just any String, there is no need.

I think you said you don't want to allow the data to change once written (only deleted).  That's what your rules are doing.  If you want the adminto be able to update a value as well you can add

```
  update() { isAdmin() }
```

to your rules.

FYI - you can evaluate these two in Bolt:

```
path /user/responses/{$uid} is Map<String, Number> {
  read()     { isCurrentUser($uid) }
  create()    { isAdmin()}
  delete()    { isCurrentUser($uid) }
}

path /user/responses2/{$uid}/{$requestID} is Number {
     read()     { isCurrentUser($uid) }
     create()    { isAdmin()}
     delete()    { isCurrentUser($uid) }
  }

isCurrentUser(uid) { auth.uid == uid }
isAdmin() { auth.admin }
```

which produces rules which have the same effect:

```
{
  "rules": {
    "user": {
      "responses": {
        "$uid": {
          "$key1": {
            ".validate": "newData.isNumber()"
          },
          ".write": "data.val() == null && auth.admin || data.val() != null && newData.val() == null && auth.uid == $uid",
          ".read": "auth.uid == $uid"
        }
      },
      "responses2": {
        "$uid": {
          "$requestID": {
            ".validate": "newData.isNumber()",
            ".write": "data.val() == null && auth.admin || data.val() != null && newData.val() == null && auth.uid == $uid",
            ".read": "auth.uid == $uid"
          }
        }
      }
    }
  }
}
```
