### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by canesin** [firebase/bolt#147]
Hi, we rely on bolt for our security. But the low amount of updates on it and the fact that the new documentation on firebase.google.com does not include it is concerning. How is the status of the project ? Is it still supported ? Is it going to be the default solution for security ?

**Comment by katowulf** [comment]
Sorry about the lack of updates here. We haven't forgotten this, just haven't gotten the new post-launch priorities together yet. The short answer is that Bolt still works, albiet with a few warts for the time being. We'll definitely do something here before long. I pinged the peeps who are putting together the priorities for security rules and asked them to post an update here as soon as we have official news, which should be soon.

**Comment by ziaukhan** [comment]
We have been using Bolt extensively for our projects as well, and had the same worries. I was sensing that the security team might be going in some other direction?

**Comment by katowulf** [comment]
If they are, I would expect it to be very similar to [this one](https://firebase.google.com/docs/storage/security/#authentication), which you'll probably agree looks uncannily similar to Bolt. But the honest truth here is that I'm not involved in those discussions, so I can't really offer specifics, other than observing that our latest iterations are still pretty close to Bolt.

**Comment by brewsoftware** [comment]
Damn, I'm a little worried at this as well. I'd appreciate an update if possible?

**Comment by sebastianovide** [comment]
+1 for bolt. 

We are not using it yet but we are consider to use it. We need a way to test our rules and Bolt seems to be the only Google supported way. 

The only Bolt documentation I could find about testing (TDD) are https://github.com/firebase/bolt/issues/80 but it won't work on Firebase 3.0.

any updates ?

**Comment by matijse** [comment]
I use https://github.com/goldibex/targaryen (with jasmine) for testing, it works pretty good.

I use Bolt to write my rules and then compile to rules.json, which I test with targaryen

**Comment by sebastianovide** [comment]
I've played with targaryen and it seems being working well. I'm just little but concerned about its low popularity and low activity in the last few months: https://github.com/goldibex/targaryen/graphs/contributors

Do  you know if how do they know if they are running exactly the same tests that Firebase run on its servers ?

**Comment by matijse** [comment]
I don't know, but they do have tests to test if their testing code tests as it should test (sorry, couldn't resist :P ).

But still, I couldn't find any other good options, and I figured it's better than nothing...

**Comment by sebastianovide** [comment]
nice one :D

I'm experimenting with this gist: https://gist.github.com/tstirrat/fda88337ce3921da0636c86a9ac85983 sent by Tim Stirrat (see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/UQ08Uf1TekA/mIvEAlzqAAAJ)

Just need to put your code in a mocha test (or Jasmine or whatever you use). It works well.... but it is online, I expect to get very slow and even get timeouts... will see when the number of test will grow.

**Comment by brewsoftware** [comment]
Hey, im just looking at the simulator upgrade now.  Problem is that the maintainers here have been a little quiet so any fixes will have to be merged externally or broken out and into a separate product. 

There is legacy support for posting rules as an admin but the docs around the 3.0 auth implementation are flakey at best. 

I will push what i have to a PR tomorrow and tag the 3.0 simulator upgrade on a separate issue.

Targaryen looks promising though.  Personally i think the simulator should be broken out into another product as it doesn't actually relate to bolt specifically.  Also on the opinion front testing offline is a must for unit testing so the inbuilt simulator is really more for system testing/integration testing.

**Comment by brewsoftware** [comment]
Update to simulator under #155 .

**Comment by brewsoftware** [comment]
On another note, do we have any updates to the state of the project? It would be good to have some of these items merged into the code base...

**Comment by sebastianovide** [comment]
Our rules files is only 126 lines long (including comments) and it already has duplication !. It will become a nightmare to maintain very soon. 
We really need something like Bolt, but we cannot use it until some clarifications are done about it. Is Google still maintaining it ? is it phasing out in favour of another tool which will integrate Storage rules ? perhaps it is being developed right now ?
I really look forward for it. It will  really complement this great platform.

In the mean time, it is harder to convince developers that Firebase is the right choice.

**Comment by mckoss** [comment]
Hi everyone!

Hang in there - Bolt is going to continue to be supported and maintained.

Sorry I've been occupied with other stuff lately - I know this project needs more love and attention.

I'll be reviewing the PRs and triaging the bugs that are in the issue tracker soon.

Thanks for your patience,
Mike
