### ISSUE TITLE
Disallow user to write empty Map .set({})

### ISSUE THREAD

**Issue by startswithaj** [firebase/bolt#149]
Given the following setup, could someone point me in the right direction of how I might be able to allow users to set a map full of allocations .set({1: allocation, 2: allocation, 3: allocation }). But not allow the write of a an empty map i.e .set({}).

```
path /user/allocations/{$uid} is Map<pUID, Allocation> {
  read()  { isCurrentUser($uid) }
  write() { isCurrentUser($uid) }
  // this seems to do nothing
  //validate() { this != null }
  //validate() { this.hasChildren() }
}
```
The doco clearly alludes to somethng 
```
ref.hasChildren(props)	implicit using "path is Type"
ref.exists()	ref != null
```
If I shouldn't be using a map, what type can I use that would allow me to set the whole object tree.
.set({1: allocation, 2: allocation, 3: allocation }) but not .set({}).

I realise that issues is probably not the best place for this question. So my apologies in advance.

**Comment by mckoss** [comment]
(better place for this would be StackOverflow - feel free to copy your question there and link to it from here).

Firebase does not have the concept of an "empty Object" in the database.  Writing .set({}) is equivalent to writing .set(null).

I think what you're trying to accomplish is:

```
type Allocation {
  foo: String;
}
path /user/allocations/{$uid} is Allocation;

path /user/allocations {
  validate() { this != null }
}
```

Note that your use of Map<> would create a second level of user ids in your database - which I don't think was intended.

**Comment by startswithaj** [comment]
Roger that and thanks for the help @mckoss. I realise now I was doing the null check to deep. The Map uses pUID which is different from the userUID. pUID refers to a reference somewhere else in the firebase. So its like userUID/Map<Puid, blah>.
