### ISSUE TITLE
Illogically strips out brackets

### ISSUE THREAD

**Issue by zeus3rd** [firebase/bolt#152]
Bolt strips out logical brackets put into rules so two sets of exclusive rules can not be declared as far as I can tell, which negates it's compatibility with things like firebase-queue

For example:
`path /a_data {
  validate() { (newData.hasChildren(['a']) && auth == null) || (newData.hasChildren('b') && auth != null) }
}`

Produces:
`"a_data": {
      ".validate": "newData.hasChildren(['a']) && auth == null || newData.hasChildren('b') && auth != null"
    },`

But expected:
`"a_data": {
      ".validate": "(newData.hasChildren(['a']) && auth == null) || (newData.hasChildren('b') && auth != null)"
    },`

**Comment by mckoss** [comment]
This looks right to me - parens are removed because && has higher operator precedence than ||.

BTW - hasChildren should not be used in a Bolt expression - use instead:

```
path /a_data {
  validate() {
    auth == null ? this.a != null : this.b != null;
  }
}
```
