### ISSUE TITLE
Regexp backslash produces wrong output / escaped backslash

### ISSUE THREAD

**Issue by brommer** [firebase/bolt#153]
A backslash in a regexp used for escaping a dot will unexpectedly be escaped in the output:
```
type UrlString extends String {
	validate() { this.length <= 200 && this.test(/.+whatever\.com\/.+/) }
}
```
produces

```
".validate": "newData.isString() && newData.val().length <= 200 && newData.val().matches(/.+whatever\\.com\\/.+/)"
```

However, the backslash should not be escaped in the output. Am I using a wrong syntax or is this a bug?

**Comment by mckoss** [comment]
The double backslash is for quoting the backslash inside the string constant.  (i.e., "\\" is a single backslash in the string).  I'll add a test in regexp.bolt to confirm - but I think the encoding is correct.
