### ISSUE TITLE
Simulator Update

### ISSUE THREAD

**Issue by brewsoftware** [firebase/bolt#155]
Update simulator to work with Firebase 3.0

Currently the REST protocol does not work with Firebase 3.0 . This thread is to discuss the way forward for the given simulator and what can be done.

**Comment by brewsoftware** [comment]
Hi Guys,
   So just some background about the new Firebase 3.0 API's.

* The NodeJS API doesn't support the "signInWithCustomToken" call. This is only supported on the client side.
* There appears to be a reserved "nonce" value in the JWT token. This alludes to the api requiring a nonce on every request. For the un-initiated this is a unique value  that can't be repeated per scope (Request, Session....). Given that we already have a unique DateTime which provides this per session I would suggest that the API is now implementing a Unique Nonce per request pattern. Saying this the REST API is probably going to be dumped for anything other than anonymous requests, a similar pattern can however still be implemented but the authentication needs to be respected.

So from the findings over the past couple of days I would suggest that the RestAPI needs to be obsoleted for Node based applications.

Luckily there is a pattern to work around the issue. Specifically we can run the "InitializeApplication" with a second parameter to include a namespace specific to the username and run requests against that specific instance. I'm currently in the process of working through this upgrade process in the background and should have something in the next couple of days.


----
From a security point of view I kind of agree that the Bearer Token authentication mechanism and most SPA architectures are broken. A nonce value would make sense so that stolen tokens can't be used to access resources. In the browser security model this usually means a Secure cookie that is tied to the bearer token as well. In a REST only world this secure cookie mechanism doesn't exists hence this is what makes me believe that they are trying to remove the reliance on it...
----

Comments welcome. I thought that given the lack of explanation over why the API has changed it might be worthwhile dragging this out from anyone closer to the API team at google...

Cheers

**Comment by brewsoftware** [comment]
Hi guys, updated Simulator tied to the 3.0 API. I will merge this on my private repo for the time being but waiting for the main build to be updated for now...

**Comment by mckoss** [comment]
Note that you can use the Bolt simulator with the 3.0 SDK - you just need to install the database secret to get the appropriate admin access via the REST interface.  I've updated the 'configure-project' command to point to the new location.
