### ISSUE TITLE
Undefined function: prior

### ISSUE THREAD

**Issue by FrankChung** [firebase/bolt#169]
I have a bolt file as follow:
```
path /test is Map<Test, String> {}

type Test extends String {
  validate() { prior(root) != null }
}
```

I got an error as:
bolt: Generating test.json...
bolt:1:1: Undefined function: prior
bolt: Could not generate JSON: 1 errors.

But if I don't put the Test type as a key of the map, it compiles correctly.

**Comment by mckoss** [comment]
Thanks for the minimal reproducible test case!  I fixed this in PR #170.
