### ISSUE TITLE
Support iterators in expressions

### ISSUE THREAD

**Issue by matjaz** [firebase/bolt#17]
For more complex validations it would be good to generate rules using loops.

```typescript
type StaticLoop {
  validate() {
    return
      this.value == true &&
      for (let i = 1; i <= 5; i = i + 2) {
        this.child(i + '_' + i).val() < this.child(i+2 + '_' + i+2).val();
      }
      && this['7_7'] < 100
      ;
  }
}
```

`".validate": "newData.value == true && newData.child('1_1').val() < newData.child('3_3').val() && newData.child('3_3').val() < newData.child('5_5').val() && newData.child('5_5').val() < newData.child('7_7').val() && newData.child('7_7').val() < 100"`

**Comment by mckoss** [comment]
Our goal for this language is to be declarative rather then imperative.  So, I don't think we'd go for a syntax like the one you describe.   Maybe something like:

    validate() { return [1 .. 5].every(function(i) { return this[i + '_' + i] < this[i+2 + '_' + i + 2]; }) && this['7 7'] < 100;

BTW - In Bolt, there is no need for .child() or .val().  Path references can use dot-notation for statically named children, and [] notation for dynamically named (variable) children.  .val() is automatically added when a path is used as a value in an expression.

**Comment by matjaz** [comment]
That works too. Just don't forget about the step (i = i+2).
Also inclusive & exclusive ranges would be great. something like CoffeScript ranges: [1..5] vs. [1...5]

**Comment by TristonianJones** [comment]
My own preference would be to not allow explicit loop constructs as we want to make sure we can offer strong guarantees about the performance characteristics of the language. For example, nested function calls are allowed, but the max stack depth will be limited to something like 10 frames. Lambda functions would be very powerful, but we should also constrain the max list size that can be processed.  

I would like to support slice operators, but would prefer not to support ranges as it would be preferable to focus the language on only the constructs needed to evaluate the input and it's odd for the script to declare the list indices outside of a type list size constraint.
