### ISSUE TITLE
Compile to triple equality operators instead of double

### ISSUE THREAD

**Issue by patrickmcd** [firebase/bolt#171]
Operators === and !== in my .bolt file become == and != upon compilation. Yet as the [Firebase docs say](https://firebase.google.com/docs/reference/security/database/#equals):

> Note:: == IS TREATED AS ===. If you use == in your security rules, it will be translated to === when the rules are run.

So might as well use the triples throughout.

**Comment by mckoss** [comment]
I don't feel strongly one way or the other, since it's not a semantic difference.  I'd be happy to review a PR if you want to make the change - note that all the example .json files would need to be changed to continue to pass the tests.
