### ISSUE TITLE
Recommended way to update single key of type?

### ISSUE THREAD

**Issue by okcoker** [firebase/bolt#175]
Consider a basic user type and it's path:

```
type User {
    name: String,
    created: Number,
    lastSignIn: Number,
}

path /users/{uid} is User {
    read() { auth != null && auth.uid == uid }
    write() {  auth != null && auth.uid == uid }
}
```

Which generates to:

```
{
  "rules": {
    "users": {
      "$uid": {
        // fails here when updating one key
        ".validate": "newData.hasChildren(['name', 'created', 'lastSignIn'])",
        "name": {
          ".validate": "newData.isString()"
        },
        "dateCreated": {
          ".validate": "newData.isNumber()"
        },
        "lastSignIn": {
          ".validate": "newData.isNumber()"
        },
        "$other": {
          ".validate": "false"
        },
        ".read": "auth != null && auth.uid == $uid",
        ".write": "auth != null && auth.uid == $uid"
      }
    }
}
```

Based on the above scenario, I have a few questions, one of which could be answered if I had a little more insight into the direction of Bolt.

- If I wanted to just update just the `lastSignIn` key, should I be adding `| Null` to everything in the type definition or is it recommended to leave the type as is but grab the whole user object, change that single key and perform the update?
- Since the `$other` key is automatically being added with a `.validate: false`, trying to update the  user data with any other key not specified in the `.hasChildren()` array will fail. So is having `newData.hasChildren(['name', 'created', 'lastSignIn'])` _and_  `$other` redundant? 

I did notice adding `| Null` to any of the keys within a type definition will not add it to the `hasChildren` array but depending on the recommended way to handle the first question, `$other` already seems to be a valid enough catch-all to me with no need for the top `.validate`. Especially since each key has it's own `.validate` method. I could be missing something here though so any wisdom would be appreciated.

**Comment by mckoss** [comment]
The validation rules operate on the final value of your data.  There is no difference between updating a single property of an existing User, vs over-writing the User whose only difference is the property you want to change.

You should only add | Null to a property that is considered "optional" in your type definition.

The reason for the $other rule is to prevent wiring non-specified properties to your data.

**Comment by okcoker** [comment]
So the last 2 comments make sense. I understand the purpose of those things but it seems there is some confusion on the first part:

Here's a screenshot from the firebase console using the rules generated by bolt. This is attempting to just update `lastSignIn` which fails because I'm not providing all the keys in that array. `newData` represents the _provided_ data value and not the final result data.

<img width="1018" alt="screenshot 2016-08-19 15 30 49" src="https://cloud.githubusercontent.com/assets/1030830/17821910/074296fa-6622-11e6-8fed-a2686531143f.png">

This is a screenshot of me adding all the keys within that array (which wouldn't work in my actual case since dateCreated is not editable after creation):
<img width="1006" alt="screenshot 2016-08-19 15 34 09" src="https://cloud.githubusercontent.com/assets/1030830/17821983/75afb29e-6622-11e6-9bd3-54bda4f1eb0c.png">

Under the hood of Firebase, and as a final result, yes, changing 1 key will only result in that 1 key being changed, but it doesn't seem like these rules let me just update 1 key. Unless of course I add `| Null` to all the members of the type definition which ultimately removes the top level `.hasChildren` validate rule. That works but feels wrong to have to add `| Null` to everything.

<img width="1011" alt="screenshot 2016-08-19 15 39 10" src="https://cloud.githubusercontent.com/assets/1030830/17822127/432a4c34-6623-11e6-81de-240c974d51b6.png">

**Comment by okcoker** [comment]
Hmm now that I think about it, maybe that's because the console doesn't let me perform an actual update and it's just overriding the whole user object?

**Comment by okcoker** [comment]
Ok so in my app I've confirmed that trying to perform an update with just that single key, fails when that `newData.hasChildren` rule is in effect. Now I'm not sure if this is a Firebase bug or I'm doing something stupid. Will keep searching.

**Comment by okcoker** [comment]
Ok so this was my fault. In trying to make the example simpler, I just needed to add a `| Null` to a couple of newly added keys in my scenario.
