### ISSUE TITLE
bolt: Unsupported RegExp modifier: g

### ISSUE THREAD

**Issue by AdrienDC** [firebase/bolt#176]
Hello guys,
what I'm trying to do is this rule: 
auth.email.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/g, '').contains(emailreformat)

But Bolt compiler says I can't use the regex modifier g for global. How to achieve that then?

If I manualy change the JSON file, I got this error message: Error saving rules - Line 102: regular expressions do not support flags other than i

Thanks

**Comment by mckoss** [comment]
replace() only supports string literal arguments as well, not regular expressions.

See: https://firebase.google.com/docs/reference/security/database/

Bolt doesn't can't add any functionality not supported by the JSON rules language.

But you can test for any illegal characters in a string with a auth.email.test(/[...]/) function in Bolt (which translates to a matches() function in JSON rules language).
