### ISSUE TITLE
firebase-bolt: command not found(Ubuntu)

### ISSUE THREAD

**Issue by piyushmishhy** [firebase/bolt#178]
Ubuntu- I have downloaded firebase-bolt. When I run ls node_modules, it is showing firebase-bolt. However, when I run into from command line, it shows- firebase-bolt:command not found.

Any help would be appreciated.

**Comment by abehaskins** [comment]
You'll need to run `npm install -g firebase-bolt` or run it locally from `./node_modules/.bin` folder.
