### ISSUE TITLE
Optional types ignored

### ISSUE THREAD

**Issue by WildWeazel** [firebase/bolt#180]
I made some changes to my rules file with 3.0.8 and found that all optional types are ignored by the compiler.

For example I added the optional child `source` to `Comment`:

```
type Comment extends Timestamped {
    ...
    status: String | Null
    source: String | Null
}
```

Old JSON:

```
        "status": {
          ".validate": "newData.isString() || newData.val() == null"
        },
```

New JSON:

```
        "status": {
          ".validate": "newData.isString()"
        },
        "source": {
          ".validate": "newData.isString()"
        },
```

I tried a union type and it still works:

```
type Foo {
  bar: String | Number
}

path /test is Foo {
  read() { true }
}
```

```
{
  "rules": {
    "test": {
      ".validate": "newData.hasChildren(['bar'])",
      "bar": {
        ".validate": "newData.isString() || newData.isNumber()"
      },
      "$other": {
        ".validate": "false"
      },
      ".read": "true"
    }
  }
}
```

But not when I change the second type to `Null`:

```
type Foo {
  bar: String | Null
}

path /test is Foo {
  read() { true }
}
```

```
{
  "rules": {
    "test": {
      ".validate": "newData.hasChildren()",
      "bar": {
        ".validate": "newData.isString()"
      },
      "$other": {
        ".validate": "false"
      },
      ".read": "true"
    }
  }
}
```

**Comment by oscar-b** [comment]
Isn't that the point of:
```
".validate": "newData.hasChildren(['bar'])",
```
vs
```
".validate": "newData.hasChildren()",
```

**Comment by mckoss** [comment]
The old behavior was a bug.  A validation rule is never run when a null value is written.

That said, the lack of a property listed in hasChildren() is sufficient to allow the field to be deleted when the parent value is written.

**Comment by gmaclennan** [comment]
If this is the case, should the docs be modified to not recommend defining types as:

```
path / is Person;

type Person {
  name: String,
  age: Number,
  isMember: Boolean,

  // Optional data (allows an Object or null/missing value).
  extra: Object | Null
}
```

I am understanding from your comment that this would be equivalent to just writing `extra: Object`. I was definitely confused for a while about why the former and latter were compiling to the same thing.
