### ISSUE TITLE
Why not just JavaScript?

### ISSUE THREAD

**Issue by elliotlarson** [firebase/bolt#183]
First, thank you for your work on this!  I think this library needs to be more of a first class citizen in the Firebase world.  If you're doing anything non-trivial with Firebase, maintaining the rules JSON can quickly become a pain.  This pretty much solves most of _my_ pain points.
  
This is less of an issue and more just a curiosity about the project.  I'm wondering why Bolt is implemented with a "JavaScript-like" syntax that needs to be parsed instead of just JavaScript.  I realize this allows for a cleaner API in places, but it seems like if the library was build with a regular JavaScript API then as a user I could leverage all the tooling that comes with JavaScript to implement my rules with Bolt.  

For example, with a `.bolt` file, I don't get syntax highlighting or code completion in my editor, which I would if the file were just JavaScript.  Also, I noticed an issue thread in this repo about implementing an import statement to break up larger `.bolt` files.  If the file was just JavaScript, then you would get a mechanism for this out of the box.  It seems like there would be some wins for going the just JavaScript route.

**Comment by mckoss** [comment]
Hi Elliot.

Interesting question about why not just JavaScript.  A DSL can be embedded inside a regular programming language.  But you then have to deal with how to manage constructs of the language that are no supported by our more constrained DSL.

There are some projects where people have made syntax highlighters for Bolt.  We are close enough to JavaScript that entering "JavaScript-mode" in your editor may provide enough help on formatting.

Our goal for Bolt was to strike a balance between expressive power and simplicity, while presenting a syntax that would feel familiar to developers.

**Comment by elliotlarson** [comment]
Okay, that makes sense.  Thanks again!

**Comment by patrickmcd** [comment]
There's a [Sublime package for Bolt syntax highlighting](https://github.com/davideast/bolt-sublime).

I've never tried it, but I'd like to see one for VSCode.

**Comment by mckoss** [comment]
@davideast Do you know if there a VSCode highlighting plugin for Bolt?
