### ISSUE TITLE
Unable to use index()

### ISSUE THREAD

**Issue by florent1933** [firebase/bolt#187]
When using index(), bolt compiler trigger an error : 
```
bolt: Generating test.json...
bolt:1:1: Unsupported method name in type statement: 'index' (allowed: 'validate', 'read', 'write', 'create', 'update', 'delete')
```

Sample of code to test index():
````
path /sports/{id} is Sport {
  read() { true }
  write() { true }
}


type Sport {
  index() {['name']}

  name: String,
  priority: Number | Null
}

````

No error, if I remove index()

**Comment by mckoss** [comment]
Sorry - isn't documented very well.  The `index()` function should be placed on the `path` that you want an index created at - not on a `type`.  It also needs to be defined at the level of parent node - not on an individual instance.  So, I think your example should be written as:

```
path /sports {
  index() {['name']}
}

path /sports/{id} is Sport {
  read() { true }
  write() { true }
}


type Sport {
  name: String,
  priority: Number | Null
}
```

See this [StackOverflow](http://stackoverflow.com/questions/32860141/why-does-this-firebase-indexon-not-work) question about where to place `indexOn` statements.
