### ISSUE TITLE
Support Mixin Type extension

### ISSUE THREAD

**Issue by matjaz** [firebase/bolt#19]
I would prefer to see mixins for types. Comparing to classes, mixins are composable allowing more flexibility.

https://github.com/Microsoft/TypeScript/wiki/Mixins

**Comment by mckoss** [comment]
I like that idea.  I would probably just allow for:

    type MyType extends BaseType1, BaseType2 {
   }

(allowing the extends Type to be a list of types).

**Comment by tomlarkworthy** [comment]
How does the validate work for a mixed in type, mix(A,B). I see a few options

mix(A,B).validate() := a.validate() BOOL_OPERATOR b.validate();

If BOOL_OPERATOR is OR, then we have a union type. If BOOL_OPERATOR is AND we have a mixin, or multiple inheritance

If we want mixins I think we should make sure the syntax can include union types later, maybe something  like (perhaps "," can be the type "&" operator)

type MyType extends BT1 & (BT2  | BT3)

What happens to the other special methods like read() and write(). If they are not specified, then they are false by default??? If they are false by default AND we apply & to all the special methods, then no mixin would ever be able to add a write rule (as one of the parents has false in it). So this is a major things to figure out. Which special methods apply to mixin behaviour? Is it just the properties that are &&ed? We need more thought.

**Comment by tomlarkworthy** [comment]
I think mixins only make sense when the behavior is orthogonal (i.e. no common variables or methods). The above issues I mentioned are due to the fact the types in Bolt are all implementing the same API surface, hence they are more difficult to mixin consistently.

**Comment by TristonianJones** [comment]
I find mixins to be nice in theory but messy in practice. The security language should be unambiguous as ambiguity would break the informal safe-by-default philosophy we've been following thus far. My own preference would be to wrap union types in another object or a special oneof {} block. 

_Oneof Operator_
This provides exactly the union type functionality that Tom describes and is more clear about the object behavior than multiple inheritance.
```
type MyType {
  type BtExtType {
    oneof {
      bta_value: BtTypeA,
      btb_value: BtTypeB;
    }
  }
  bt_value: BtBaseType,
  bt_ext_value: BtExtType;
}
```

_Wrapped Optional Types_
This provides similar behavior to what union type syntax Tom proposed, but adds an implicit Null type in the (|).
``` 
type MyType {
  type BtExtType {
    bta_value: BtTypeA?,
    btb_value: BtTypeB?;
  }
  bt_value: BtBaseType,
  bt_ext_value: BtExtType
}
```

**Comment by tomlarkworthy** [comment]
I don't understand your example. With a mixin I expect the property names to be interleaved, but I am reading your example as prefixing the properties under either bta_value or btb_value.

its the .validate and the .extensible functions I see no sane way of merging for a mixin. We could set them to false and force the user to write new ones from scratch. Or we could OR them. 

Come to think about it. I am not sure what the Bolt behavior is when you do 
1. a single inheritance subclass.
2. a single inheritance subclass with the subclass defining a .validate
3. a type with no .validate defined (I assume validate is defaulting to true in that case).

**Comment by TristonianJones** [comment]
I'm suggesting that we not support mixins, but rather support `oneof` to indicate type unions. This somewhat the functionality that's being addressed by mixins but slightly more verbose without interleaved properties. It does have clear behavior for .validate though

**Comment by TristonianJones** [comment]
Sorry Tom, I feel a bit silly. Consider my last post a stream of Monday morning semi-consciousness. I realize now that what I stated basically already exists and much of what one would want from a mixin is covered by a type union and the .validate() has clear semantics. So I'm in agreement, let's not support mixins, they invite ambiguity / aren't compatible with the secure-by-default philosophy.

**Comment by matjaz** [comment]
My idea of types was code reuse. Use case for mixins is merging functionality from different types.

`
type FreezedObject {
  extensible(propertyName) { return false; }
}

type NonEmptyString extends String {
  // `this` is string value
  validate() { return this.length > 0; }
}

type Schema {
  isCreate() { return !data.exists(); }
}

type Person {
  name: NonEmptyString
}

// multiple mixins
type User extends FreezedObject, Schema, Person {
  lastActive: UnixTimestamp

  validate() {
    return this.isCreate();
  }
}
`

In TypeScript mixins are orthogonal. Maybe orthogonal mixins can be a start.

**Comment by mckoss** [comment]
I'm finding this proposal too complex - I found even the TypeScript mixins explanation pretty convoluted.

Orthogonal types can be extended serially if desired - and you can also use Generic types, more flexibly like:

```
type User extends FreezedObject<Schema<Person>>;
```
