### ISSUE TITLE
feature request: Treat colon as part of string for dot notation

### ISSUE THREAD

**Issue by patrickmcd** [firebase/bolt#192]
With flat data structures / denormalization in mind, I use a variation of [dot notation for higher detail collections](http://stackoverflow.com/a/9868505/1341838). But in Firebase, dots are reserved and can't be in node keys, so I use the colon.

So instead of:
```
"collection": {
  "$itemId": {
    "member1": "1",
    "member2": "2",
    "member3": "3"
  }
}
```

I flatten it to:

```
"collection": {
  "$itemId": {
    "member1": "1"
  }
}

"collection:member2": {
  "$itemId": "2"
}

"collection:member3": {
  "$itemId": "3"
}

```

I like this organizational practice and it makes the database in the FB console look pretty. The one slight annoyance in Bolt is that the colons force me to use bracket notation to access the flattened collections:

```
prior(root).path.to.collection[itemId].whatever
// vs.
prior(root).path.to.["collection:member2"][itemId].whatever
```

Would it be possible to allow the colon (and other non-reserved characters) to be treated as `\w` characters so dot notation could be used for property access? Then we could do:

```
prior(root).path.to.collection:member2[itemId].whatever
```

The colon presents no issues in path declarations:

```
path / {

  /collection/{itemId} {
    read() {true}
    write() {true}
  }

  /collection:member2/{itemId} {
    read() {true}
    write() {true}
  }

  ...

}
```

It would be nice to look at my Bolt file and immediately know that in any brackets I am intentionally creating a string from variables, instead of taking a second to see if I'm just escaping one of my colon separators.

I'm considering switching to the underscore as my separator, but that conflicts with other uses for the underscore.

**Comment by rockwotj** [comment]
While possible, I don't think this leads to a clear/maintainable rules file, besides `:` is an allowed key as well as `_` or most other characters other than what is documented here: https://firebase.google.com/docs/database/web/structure-data#how_data_is_structured_its_a_json_tree
