### ISSUE TITLE
Using bolt to indexOn some fields

### ISSUE THREAD

**Issue by mrdadah** [firebase/bolt#196]
Is there is any possibility to create index data as shown here : https://firebase.google.com/docs/database/security/indexing-data

**Comment by htkm** [comment]
Do you mean the bolt equivalent of `.indexOn` which is described [here](https://github.com/firebase/bolt/blob/master/docs/language.md#rules)?

**Comment by nuba** [comment]
For the record, it works on a path declaration, but it breaks when inside a type declaration.

`bolt:1:1: Unsupported method name in type statement: 'index' (allowed: 'validate', 'read', 'write', 'create', 'update', 'delete')`

**Comment by judewang** [comment]
@nuba @mrdadah Hi, I do have the issue, too. I've found the solution, check out [this](https://github.com/firebase/bolt/issues/187). Just add the `index()` in `path` section rather then `type` .
