### ISSUE TITLE
Add .key() method to RuleDataSnapshot

### ISSUE THREAD

**Issue by mckoss** [firebase/bolt#20]
(from @matjaz)

Adding key() method to RuleDataSnapshot would add more flexibility to
validation when using $ variables.

For example:

1. {
2. $item: {
3. ".validate": "newData.key().matches(/^foo/)"
4. }
5. }

Please let me know your opinion.

**Comment by mckoss** [comment]
There are a couple of changes between Blaze and Firebase JSON Rules:

- In Bolt, we use "this" instead of "newData".
- Because we will be deprecating the special RuleDataSnapshot methods ref.child() and ref.val() in favor of ref.child or ref[child] syntax, we're not looking to add additional snapshot methods.

(My plan for snapshot methods and the match method for strings is to migrate them to Bolt global functions instead - so there is no chance of accidental name collision).

**Comment by mckoss** [comment]
Also, just to make sure I understand you, $item would be the same as newData.key() if your case.  Is there a problem with using $item?

**Comment by matjaz** [comment]
Actually with above example I was referring to Firebase rules with no connection to bolt.

Yes in bolt we could use
```
{
  $item: {
    ".validate": "$item.matches(/^foo/)"
  }
}
```

But if I understand correctly that is currently not possible to translate to Firebase rules or is it?

**Comment by mckoss** [comment]
You can write that directly in Firebase JSON rules since $item is treated as a string value when rules are evaluated.

**Comment by matjaz** [comment]
I didn't know that! Thanks!
