### ISSUE TITLE
Can bolt be implemented in nativescript with firebase? Examples?

### ISSUE THREAD

**Issue by sagearbor** [firebase/bolt#201]
Can anyone tell me if bolt has been implemented in nativescript and hopefully provide links to github examples, I was unable to find any.  Im setting up an nativescrpt app using angular2 with users joining multiple groups, where groups can be nested (which it sounds like bolt would be great for), but its such an common problem I assumed there would be tons of examples on github but I cant find them.

**Comment by patrickmcd** [comment]
Bolt has precisely zero to do with your choice of front end framework.

**Comment by sagearbor** [comment]
I didnt find any tie-ins to nativescript ... I was thinking command line implementation "tns ..." .  So Ill take it you can use bolt to create files and just put them in the right place but not an automated part of the build process.  I am not investigating but will close ticket.
