### ISSUE TITLE
Support for Realtime Database query based security rules

### ISSUE THREAD

**Issue by PrinceCornNM** [firebase/bolt#224]
Realtime Database now has [query based security rules](https://firebase.googleblog.com/2018/01/introducing-query-based-security-rules.html). This new feature allows users to write new security rules. Can Bolt support this new addition?

**Comment by 0xClpz** [comment]
I'm not sure if that helps but you can already use them just fine they dont have their own bolt syntax just yet.
```Bolt
path /todos {
    read(){
        query.orderByChild == 'userId' && query.equalTo == auth.uid
    }
}
```

compiles to
```JSON
"todos": {
    ".read": "query.orderByChild == 'userId' && query.equalTo == auth.uid"
 },
```

**Comment by precompro** [comment]
@0xClpz You sir are amazing!!

**Comment by rockwotj** [comment]
Looks like this works, if there are more bolt specific syntax desired, please open a new issue.
