### ISSUE TITLE
Property names should allow full scope of Firebase keys.

### ISSUE THREAD

**Issue by mckoss** [firebase/bolt#38]
In order to allow for all [Firebase-compatible keys](https://www.firebase.com/docs/web/guide/understanding-data.html#section-limitations) in type statements, we need to be able to "quote" key values in the grammar.

For example:

```
type T {
  '0,0': Boolean,
}
```
Should be legal.  Propose allowing `String: Type` in addition to `Identifier: Type` in the grammar for property definition.

**Comment by tomlarkworthy** [comment]
+1
