### ISSUE TITLE
Static typing

### ISSUE THREAD

**Issue by mckoss** [firebase/bolt#42]
The code quality and readability would be improved by incorporating static typing of the sources.  Plan to migrate the code to TypeScript.

**Comment by tomlarkworthy** [comment]
I can have a go at this. I recently setup a gulp watchable typescript project with source-map support. Its fiddly if you are coming from a blank slate.

**Comment by mckoss** [comment]
That would be cool if you have time.  The current project is designed to publish to npm via the lib (and bin) directory (the only build product is from peg parser to /lib, and some browserify bundles for browser testing).

I'm guessing we would move all the build products to /dist and update the publishing rules to publish the post-processed files.

**Comment by mckoss** [comment]
Done!

**Comment by mckoss** [comment]
Our build is now using TypeScript.  ast.ts is now typed - just have to go through the other source files to get all exports with well defined types.
