### ISSUE TITLE
Object with properties should not allow property extension

### ISSUE THREAD

**Issue by mckoss** [firebase/bolt#47]
In the 'safe by default' vein, we should not allow unspecified properties to be written to a model that has named properties specified.

Accomplish by adding "$other": {".validate": "false"} is parallel with the explicitly names properties.

**Comment by mckoss** [comment]
a40b4bb1e619acdc246ac0eec63e00e0767f77ca fixes

**Comment by mckoss** [comment]
The 'koss-extensible' branch has a fix for this.

**Comment by matjaz** [comment]
:+1: https://github.com/firebase/bolt/issues/30#issuecomment-137475774

**Comment by mckoss** [comment]
Fixed by 3a5b4bb3d7e6b357e71a3b8f4c77ad16591b4686
