### ISSUE TITLE
/object/$userid/property/ vs /object/$userid/property

### ISSUE THREAD

**Issue by kermankohli** [firebase/bolt#71]
Hey, so I was testing out my rules on the simulator when I came across an error when I tried to write to the root. Turns out the rule /object/$userid/property/ was being enforced on the root, I removed the trailing slash and it removed it from the root. Not sure why that happened but it's a pretty weird bug that needs to be squashed...

**Comment by mckoss** [comment]
I think I just fixed this today - see issue 66.
