### ISSUE TITLE
.exists() creates invalid Firebase rules

### ISSUE THREAD

**Issue by aputinski** [firebase/bolt#75]
The following Bolt rules:

```
path /some/$path {
  validate() = root.items[$path].exists();
}
```

output the following invalid Firebase rules:

```json
{
  "rules": {
    "some": {
      "$path": {
        ".validate": "newData.parent().parent().child('items').child($path).child('exists')()"
      }
    }
  }
}
```

**Comment by matjaz** [comment]
use `!= null`

**Comment by aputinski** [comment]
What about other functions like `.hasChild()`?

`this.hasChild('key')` => `newData.child('hasChild')('key')`

**Comment by mckoss** [comment]
Bolt tries to simplify and normalize the way data is referenced as opposed to using many custom methods.  [A good summary of how references in the JSON format should be written in Bolt](https://github.com/firebase/bolt/blob/master/docs/language.md#ruledatasnapshot-methods).

**Comment by aputinski** [comment]
That makes sense. Totally missed the language reference. Bolt has been a pleasure to use so far. Great work!

**Comment by mckoss** [comment]
Thank you!

On Wed, Nov 11, 2015 at 4:42 PM, Adam Putinski <notifications@github.com>
wrote:

> That makes sense. Totally missed the language reference. Bolt has been a
> pleasure to use so far. Great work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/bolt/issues/75#issuecomment-155958608>.
>



-- 
+Mike Koss <https://plus.google.com/+MikeKoss>
(425) 246-7701 (m)

**Comment by startswithaj** [comment]
Hi guys, thanks for bolt its awesome. I'm really struggling to figure out the pattern for exists().

I want to check that a record in another branch exists with the UID before it gets added to the other branch.

I have a validation rule:

```
profileExists(uid) { root.child('profiles').child(uid) != null }
```
Error: Rules Syntax Error: 1:1410: Invalid != expression: left operand is not a number, boolean, string, or null.

Ive also tried this

```
profileExists(uid) { root.child('profiles').child(uid).exists()
```
bolt:1:1: Undefined function: newData.parent().parent().child('profiles').child($uid).exists

I'm really at a loss to what I'm doing wrong here. It's driving me crazy.

```
path /profilesApproved/$uid is ApprovedProfile {
  read() = true;
  write() = isJake();
  validate() = podcastExists($uid);
}
```

and I've tried it this way

```
type Profile {
  validate() = profileExists(this.key);
  name: String
  author: String
  blurb: String
  imageUrl: String // maybe just image name
}
```

**Comment by startswithaj** [comment]
#94 solved it for me 

profileExists(uid) { root.child('profiles').child(uid).val() != null }

**Comment by mckoss** [comment]
Don't use child() in Bolt.

root,profiles[uid] != null

Is what you want.
