### ISSUE TITLE
DSL for testing

### ISSUE THREAD

**Issue by tomlarkworthy** [firebase/bolt#8]
The bulk of testing in blaze is done through a DSL:

1 example per file:
https://github.com/firebase/blaze_compiler/tree/master/test/scenarios
many examples per file:
https://github.com/firebase/blaze_compiler/blob/master/test/anticases/objects.yaml

This is the quickest way to react to user bugs. Given that in bolt, putting source code inside source code is already a problem (e.g. decision to use ' instead of " due to escaping issues). I suggest Bolt should move to a more productive test harness, it will pay for iteself over the long term

**Comment by mckoss** [comment]
The added "simulator" addresses Bolt testing in a DSL-like embedded language.
