### ISSUE TITLE
Error on hyphen in type property

### ISSUE THREAD

**Issue by ziaukhan** [firebase/bolt#81]
The following file is giving an error because of hyphen in "data-created", but it is allowed in rules syntax:

type User {
  email: String,
  firstName: String,
  lastName: String,
  data-created: Number,
  status: Number
}

isCurrentTime(timestamp) = timestamp == now;

isAnyAuthUser() = auth != null;

isAuthUser(userID) = auth.uid == userID;

path /users {
  read() = isAnyAuthUser();
}

path /users/$user is User {
  write() = isCurrentTime(this.dateCreated) && isAuthUser($user);
}

**Comment by mckoss** [comment]
See issue #38.
