### ISSUE TITLE
Duplicate rules: rules:

### ISSUE THREAD

**Issue by seanblezard** [firebase/bolt#84]
Hi, 

Just tried this - when I do a firebase deploy:rules from the command line it deploys to Firebase with an extra level of rules:{ i.e. rules{rules:{}} instead of rules:{}

Weird.

Sean

**Comment by mckoss** [comment]
Hi Sean,

I've not seen this issue before.  Do you have a sample of what your Bolt file looks like? (I'd like to reproduce it - could be a problem with Bolt or the firebase-tools command line).

Also - what versions of each are you using.  The current Bolt compiler is 0.5.0 (firebase-tools is 2.1.0).

@mbleigh

**Comment by mbleigh** [comment]
@seanblezard this is probably an issue with firebase/firebase-tools -- can you file it against that? Thanks!
