### ISSUE TITLE
Hyphen Sign not working after Compiled

### ISSUE THREAD

**Issue by uqutub** [firebase/bolt#91]
When we are compiling the bolt to json using hypen sign, example.

in bolt:
----------
type Test1 {
validate() = this.team-member.length >= 10; 
"team-member": String
}
path /teamMember is Test1 {
	read() = true;
	write() = true;
}

after complies:
-------------------
{
  "rules": {
    "teamMember": {
      ".validate": "newData.hasChildren(['team-member']) && newData.child('team').val() - member.length >= 10",
      "team-member": {
        ".validate": "newData.isString()"
      },
      "$other": {
        ".validate": "false"
      },
      ".read": "true",
      ".write": "true"
    }
  }
}

**Comment by uqutub** [comment]
there is way around, but not for proper solution.

type ChkString extend String{
	validate() = this >= 10;
}


type Test1 {
	validate() = this.team-member.length >= 10; 
	"team-member": ChkString
}


path /teamMember is Test1 {
	read() = true;
	write() = true;
}

**Comment by mckoss** [comment]
In order to use a path key that has a hyphen in it, you cannot use dot-notation (since the hyphen will look like a minus sign in an expression).  Instead, use the bracket notation like so:

```
type Test1 {
  validate() = this['team-member'].length >= 10;

  "team-member": String
}

path /teamMember is Test1 {
  read() = true;
  write() = true;
}
```
