### ISSUE TITLE
Properties with only read/write false rules are omitted - even if sibling to wildcard property.

### ISSUE THREAD

**Issue by fabiozaffani** [firebase/bolt#97]
Firebase work in a permissive mode by default (everyone allowed to read and write anything) I always set the paths and objects to read and write to false. However doing that inside a *.bolt file will translate to nothing. Let's use the following rules as an example:

```
path / {
    read() = false;
    write() = false;
}
```
Nothing get's generated in the resulting json file, the desired effect, however, should be 

```
{
  "rules": {
    ".read": "false",
    ".write": "false"
  }
}
```

**Comment by fabiozaffani** [comment]
Just an update, for now i'm using the following statement to emulate the "false".

```
path / {
    read() = 1 == 0;
    write() = 1 == 0;
}
```
Since firebase will parse the value inside the ".read" and ".write" it will set consider it as "false"

**Comment by mckoss** [comment]
Firebase is read==false and write==false by default, su there is no need for this.

**Comment by jacob-israel-turner** [comment]
There is a need for this.  I want to make only one key un-readable and un-writable, but every sibling key readable and writable when authed.  @fabiozaffani's workaround makes this possible, but compiling `write() = false` should be an option.

**Comment by mckoss** [comment]
write() = false is a NO-OP in Firebase (JSON) rules.  This is because all write rules are OR-ed together in the hierarchy - there is no way to make a child property unwritable when it has already been made writable by a parent rule.

**Comment by jacob-israel-turner** [comment]
I'm not talking about parent keys, but siblings.

```
path /parent {
  read() = auth !== null;
  /someKey {
    write() = false; 
  }
  /$all_other_keys {
    write() = auth !== null;
  }
}
```

I want to make `someKey` unwritable, but every other key writable if you're authed.  This compiles to:

```
"parent": {
  "someKey": {
    "$all_other_keys": {
      ".write": "auth != null"
    }
  },
  ".read": "auth != null"
}
```

Which makes every key (including `someKey`) writable with auth.

I've realized that our model was actually different, so this doesn't affect me.  But it could certainly match a future use-case.

**Comment by mckoss** [comment]
someKey is already unwritable by default.  You current example compiles to:
```
{
  "rules": {
    "parent": {
      "$all_other_keys": {
        ".write": "auth != null"
      },
      ".read": "auth != null"
    }
  }
}
```
Since `someKey` is not mentioned in any rule - it will not be writable (or readable) in Firebase.

**Comment by jacob-israel-turner** [comment]
Uh, then I'm confused.

From my understanding, `$all_other_keys` is an alias for every key under `parent`, meaning, if I have the data:
```json
{
  "parent": {
    "this_is_a_key": "foo",
    "someKey": "bar",
    "this_is_another_key": "baz"
  }
}
```
then all three keys (`this_is_a_key`, `someKey`, and `this_is_another_key`) will now be writable, given the rules that you just posted.

Am I missing something?

**Comment by mckoss** [comment]
(I edited my last response - I get it now!)

**Comment by jacob-israel-turner** [comment]
Ah yes, exactly.  :)

**Comment by mckoss** [comment]
Another work-around is to apply a type to someKey - which will emit a node for it in the JSON tree:
```
path /parent {
  read() = auth !== null;
  /someKey is String;
  /$all_other_keys {
    write() = auth != null;
  }
}
```
Generates
```
{
  "rules": {
    "parent": {
      "someKey": {
        ".validate": "newData.isString()"
      },
      "$all_other_keys": {
        ".write": "auth != null"
      },
      ".read": "auth != null"
    }
  }
}
```
