### ISSUE TITLE
Cannot compile anything!

### ISSUE THREAD

**Issue by mm-gmbd** [firebase/bolt#98]
I know this seems ridiculous, but I can't compile anything, not even the simplest of rules. I mentioned this on the now closed (but probably should be re-opened) #92.

Even the following fails:

    path /path/data {
      read():   true
      write():  false
    }

Generates the error:

    bolt:1:1: Expected comment, end of input function definition, path statement, type statement or whitespace but "p" found.

This is definitely a *path statement*, so what's the deal?

**EDIT:**
Is there some sort of compatibility issue with Node perhaps?

Running the following on Windows x64:

```
node -v:           5.3.0 (stable)
npm -v:            3.3.12
firebase-bolt -v:  0.5.0
```

**Comment by mckoss** [comment]
The problem is in the read and write syntax.  You need to use an = sign instead of a colon.

    read() = true;

Sorry the error message was not very helpful.

**Comment by mm-gmbd** [comment]
Derp. I was coming from Blaze (YAML) and wasn't paying close enough attention.

Thanks!

**Comment by mckoss** [comment]
It's quite allright.  I blame poor error handling from the parser.

**Comment by scriby** [comment]
Ran into this as well. +1 for better error message.

**Comment by jacob-israel-turner** [comment]
+1 to @scriby, missing semicolon on validate expression triggers this error message.
