### ISSUE TITLE
Why does root compile to data.parent().parent().parent()...?

### ISSUE THREAD

**Issue by scriby** [firebase/bolt#99]
Because Firebase supports root directly in its security rules, I'm wondering why bolt doesn't use it and instead calls parent multiple times. I've got some deep paths where it expands out several parents() that make it pretty hard to read.

**Comment by mm-gmbd** [comment]
Just saw this today as well. I'm not sure how the security rule engine works under the hood, but I would think something like `.parent().parent().parent()...` would be less efficient than a direct reference to root, but that's just a guess.

**Comment by mckoss** [comment]
Firebase does not have a `newRoot` variable (as `newData` is to `data`).  Use of root in a write or validate rule, will emulate `newRoot
